name: 'Asana GitHub Actions'
description: 'Asana GitHub Actions'
author: belloq
inputs:
  asana-secret:
    description: 'Asana Personal Access Token'
    required: true
  action:
    description: 'The action to be performed'
    required: true
  comment-text:
    description: 'Comment text'
    required: false
  comment-pinned:
    description: 'Comment is pinned'
    required: false
    default: false
  custom-field-id:
    description: 'Custom field ID'
    required: false
  custom-field-value:
    description: 'Custom field value'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
